services:
  api:
    container_name: vue-backend
    build: ./learning-vue-backend
    command: npm run dev
    ports:
      - '3000:3000'

  frontend:
    container_name: vue-frontend
    build:
      context: ./learning-vue-frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'

  mongo_db:
    container_name: MongoDB
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo_data: 